github: sxiii
issuehunt: sxiii
ko_fi: sxiii
liberapay: sxiii
open_collective: sxiii
otechie: sxiii
patreon: sxiii
# N/A
# LFX Mentorship (formerly CommunityBridge)	community_bridge: PROJECT-NAME
# tidelift: PLATFORM-NAME/PACKAGE-NAME
